version: "3.1"
services:
  webb:
    build: .
    depends_on:
      - postgres
    ports:
      #     - <port of localhost>:<port of container>
      - 8000:8000
    #    env_file:
    #      - ./.env
    #------- volumes use: đồng bộ hóa giữa local vs container. Nên khi update local thì container cũng update theo
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE=postgresql
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=firstapi
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7q3
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
#    networks:
#      - backend
  postgres:
    image: postgres
#    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
#      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-db:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    networks:
#      - backend
volumes:
  postgres-db:

#networks:
#  backend:
#    driver: bridge
