version: "3.1"
services:
  webb:
    image: 102160170/fastapi
    depends_on:
      - postgres
    ports:
      #     - <port of localhost>:<port of container>
      - 80:8000
    #    env_file:
    #      - ./.env
    #------- volumes use: đồng bộ hóa giữa local vs container. Nên khi update local thì container cũng update theo
    #    volumes:
    #      - ./:/usr/src/app:ro
    #    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE=${DATABASE}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  #    networks:
  #      - backend
  postgres:
    image: postgres
    #    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    #      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-db:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    networks:
#      - backend
volumes:
  postgres-db:

#networks:
#  backend:
#    driver: bridge
